// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wave_application.Datas;

#nullable disable

namespace waveapplication.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20230731143935_WaveTest")]
    partial class WaveTest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("wave_application.Models.Assemblage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Article")
                        .HasColumnType("int");

                    b.Property<int>("Carton")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FinOf")
                        .HasColumnType("bit");

                    b.Property<bool>("FinPalette")
                        .HasColumnType("bit");

                    b.Property<string>("Of")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Palette")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<bool>("Supprimer")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Assemblages");
                });

            modelBuilder.Entity("wave_application.Models.BackupAssemblage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Article")
                        .HasColumnType("int");

                    b.Property<int>("Carton")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FinOf")
                        .HasColumnType("bit");

                    b.Property<bool>("FinPalette")
                        .HasColumnType("bit");

                    b.Property<string>("Motif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Of")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operateur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BackupAssemblages");
                });

            modelBuilder.Entity("wave_application.Models.BackupInjection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Article")
                        .HasColumnType("int");

                    b.Property<int>("Carton")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FinPalette")
                        .HasColumnType("bit");

                    b.Property<string>("Motif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Of")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operateur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BackupInjections");
                });

            modelBuilder.Entity("wave_application.Models.BackupQualite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Of")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operateur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Palette")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BackupQualites");
                });

            modelBuilder.Entity("wave_application.Models.BackupTremie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArticleAssemblage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Externe")
                        .HasColumnType("bit");

                    b.Property<string>("Motif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTremie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfAssemblage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfComposant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operateur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperateurModif")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BackupTremies");
                });

            modelBuilder.Entity("wave_application.Models.CartonJDE", b =>
                {
                    b.Property<string>("CN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CartonPalette")
                        .HasColumnType("int");

                    b.Property<string>("CartonsRouleaux")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumArticle")
                        .HasColumnType("int");

                    b.Property<string>("Piece")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CartonJDE");
                });

            modelBuilder.Entity("wave_application.Models.Delai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Delais")
                        .HasColumnType("int");

                    b.Property<string>("Libelle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Delais");
                });

            modelBuilder.Entity("wave_application.Models.Imprimante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomImprimante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomPc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Imprimantes");
                });

            modelBuilder.Entity("wave_application.Models.Injection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Article")
                        .HasColumnType("int");

                    b.Property<bool>("Bloquer")
                        .HasColumnType("bit");

                    b.Property<int>("Carton")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Delai")
                        .HasColumnType("int");

                    b.Property<string>("Emplacement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FinPalette")
                        .HasColumnType("bit");

                    b.Property<string>("Libelle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Of")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operateur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Palette")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<bool>("Supprimer")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Injections");
                });

            modelBuilder.Entity("wave_application.Models.OfEncours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArticleAssemblage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CartonComposant")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("OfAssemblage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfComposant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operateur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tremie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OfEncours");
                });

            modelBuilder.Entity("wave_application.Models.Reimpression", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Carton")
                        .HasColumnType("int");

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Of")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reimpressions");
                });

            modelBuilder.Entity("wave_application.Models.TArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clé_GL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeArticle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeArticleClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodeEANCarton")
                        .HasColumnType("int");

                    b.Property<int>("CodeEANPalette")
                        .HasColumnType("int");

                    b.Property<int>("CodeJDE")
                        .HasColumnType("int");

                    b.Property<string>("CodePoids")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionGL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuréeDeVie")
                        .HasColumnType("int");

                    b.Property<string>("Libelle1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibelleArticleClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibelleUnite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modèle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pharma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Poids")
                        .HasColumnType("float");

                    b.Property<double>("Prix")
                        .HasColumnType("float");

                    b.Property<string>("Unite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TArticles");
                });

            modelBuilder.Entity("wave_application.Models.Tremie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArticleAssemblage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeArticle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Externe")
                        .HasColumnType("bit");

                    b.Property<string>("NumeroTremie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfAssemblage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfComposant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operateur")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tremies");
                });

            modelBuilder.Entity("wave_application.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Supprimer")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
